// Generated by CoffeeScript 1.8.0
(function() {
  window.SpeedTest = function(testFunction, testParams, testRepetition) {
    this.testFunction = testFunction;
    this.testParams = testParams;
    this.testRepetition = testRepetition;
    return this.average = 0;
  };

  SpeedTest.prototype = {
    startTest: function() {
      var beginTime, endTime, i, sumTime, _i, _ref;
      sumTime = 0;
      for (i = _i = 0, _ref = this.testRepetition; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        beginTime = +new Date();
        this.testFunction(this.testParams);
        endTime = +new Date();
        sumTime += endTime - beginTime;
      }
      this.average = sumTime / this.testRepetition;
      return console.log("Average execution across " + this.testRepetition + ": " + this.average + " ms.");
    }
  };

}).call(this);

//# sourceMappingURL=cs_speedtest.js.map
